server:
  port: 9090

spring:
  profiles:
    active: local

  #  ANSI
  output:
    ansi:
      enabled: ALWAYS

  #  DEVTOOLS
  devtools:
    restart:
      enabled: true

# LOGGING
logging:
  level:
    root: error
    com.joje.*: debug

# JWT
jwt:
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
  access-token-expire: 60
  refresh-token-expire: 120


---
# LOCAL
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4406/sudom
    username: ENC(0/cMqN7QTjW4EQuz4sraGg==)
    password: ENC(n9rDws6yHK8quZHqh6O2K3O/YjkiKP5z)
